[package]
name = "dataset"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies.flume]
version = "0.11.0"
default-features = false

[dependencies]
pyo3 = { workspace = true }
once_cell = { workspace = true }
burn = { workspace = true }

