[package]
name = "train"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset = { workspace = true }
vae = { workspace = true }
burn = { workspace = true }
serde = { workspace = true }
rand = "0.8.5"
plotly = "0.8.4"
