[package]
name = "vae"
version = "0.1.0"
edition = "2021"

[dependencies]
dataset = { workspace = true }
burn = { workspace = true }
serde = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
burn = { workspace = true, features = ["train"]}
