[package]
name = "inference"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dataset = { workspace = true }
train = { workspace = true }
vae = { workspace = true }
pyo3 = { workspace = true }
once_cell = { workspace = true }
burn = { workspace = true }

